spring.application.name=api

server.port=9000

# Cette propriété permet de différer l'initialisation de la source de données jusqu'à ce que le contexte Spring soit complètement initialisé. 
# Cela peut être utile pour éviter des problèmes liés à l'ordre d'initialisation des beans dans certaines configurations.
spring.jpa.defer-datasource-initialization=true 

logging.level.root=ERROR
logging.level.com.openclassrooms=INFO
logging.level.org.springframework.boot.h2console.autoconfigure=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# pour activer la console H2 dans l'application Spring Boot
spring.h2.console.enabled=true